### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234",
  "nickname": "테스터"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}

### 할 일 추가
POST http://localhost:8080/api/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpZCI6MSwidXNlcl9pZCI6InRlc3RAdGVzdC5jb20iLCJuaWNrbmFtZSI6Iu2FjOyKpO2EsCIsImlhdCI6MTc3NDE2Nzk2NCwiZXhwIjoxNzc0MjU0MzY0fQ.R9h_7ZZ7HoYGLYFDeF4blr6HM5seeLB2T63Neq95yH7R1tg_t-iTLueWe1IZlcC1

{
  "content": "스프링 공부하기",
  "date": "2026-03-22"
}

### 할 일 조회
GET http://localhost:8080/api/todos?date=2026-03-22
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpZCI6MSwidXNlcl9pZCI6InRlc3RAdGVzdC5jb20iLCJuaWNrbmFtZSI6Iu2FjOyKpO2EsCIsImlhdCI6MTc3NDE2Nzk2NCwiZXhwIjoxNzc0MjU0MzY0fQ.R9h_7ZZ7HoYGLYFDeF4blr6HM5seeLB2T63Neq95yH7R1tg_t-iTLueWe1IZlcC1