### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234",
  "nickname": "테스터"
}

### 로그인 (먼저 실행하면 토큰 자동 저장!)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}

> {% client.global.set("token", response.body.token); %}

### 할 일 추가
POST http://localhost:8080/api/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "스프링 공부하기",
  "date": "2026-03-22"
}

### 할 일 조회
GET http://localhost:8080/api/todos?date=2026-03-22
Authorization: Bearer {{token}}

### 전체 랭킹
GET http://localhost:8080/api/rank

### 내 정보
GET http://localhost:8080/api/rank/userinfo
Authorization: Bearer {{token}}